### ISSUE TITLE
User Auth MVP review

### ISSUE THREAD

**Issue by minucos** [minucos/Straya#2]
Hi Elliot

I believe I have completed my first MVP for user auth.

Project is up on Heroku at [https://straya.herokuapp.com/#/](url)

Let me know your thoughts and what I need to fix up.

thanks!

Andy

**Comment by evhumphrey** [comment]
- [ ] Make sure to update your wiki so the live link is there

## Styling

As the first styling feedback, I'll leave some details of how you might change it: 

### Splash
- [ ] Remove the margin on the body
- [ ] Add a margintop and or padding top on your splash page div (to push it down below the nav)
- [ ] I'd change the body color to white
- [ ] Widen the two buttons on the splash
- [ ] Reduce height and/or padding on those buttons
- [ ] Lower border radius on those buttons
- [ ] Lighten the border
- [ ] Light the text color
- [ ] Reduce font size
- [ ] Change the `Already a user link? Log in` to only have a link on the `Log in` part

### Nav
- [ ] Make logo smaller to match size of strava's logo
- [ ] Tweak log in button size a bit (make it a tiny bit smaller width and height), and reduce text size

### Login Page
- [ ] Add padding top to the session box to push it down a bit
- [ ] Add the demo log in button (where the facebook button would be)
- [ ] Add `box-sizing: border-box` to your inputs`
- [ ] Add a padding to your inputs on the left and right
- [ ] Reduce the font size
- [ ] Change background color of inputs to be darker (like stravas); but when `:focus`, you can style it differently (lighter)
- [ ] Change the button to Sign Up in the nav bar
- [ ] Style your login button
- [ ] Add the text "Or log in with email"


It should look something like: 

![screen shot 2019-02-28 at 5 34 02 pm](https://user-images.githubusercontent.com/6361824/53610350-55548a80-3b7f-11e9-9685-d859e6a399dc.png)

![screen shot 2019-02-28 at 5 11 26 pm](https://user-images.githubusercontent.com/6361824/53610363-61d8e300-3b7f-11e9-9a7a-73c7d7646c4f.png)

**Comment by minucos** [comment]
Hi Elliot

List of changes are now complete. Let me know if there is anything else I should change before moving on, thanks!

Andy

**Comment by evhumphrey** [comment]
Sweet, looks good!

Some minor changes: 
- [ ] On the unfocused inputs in your form, change the text color to white
- [ ] Make your "Join Straya Today, it's Free" font smaller", and give it a bit more vertical padding
- [ ] Change the button in your nav bar to link to the other form (so if you're on log in, it should show "Sign Up")
- [ ] Use 100**vh** instead of 100vw for the height of your splash
- [ ] In Sign up form, Change "Already a user? Login!" to "Already a user? Log in!"

**Comment by minucos** [comment]
Hi Elliot

Completed the changes as requested. Let me know if there are any other changes you think I should make!

Also, I should be on track for completing my routes by the end of this evening, for submission anyway! I'll let you know.

thanks

Andy

**Comment by evhumphrey** [comment]
Sweet make sure to style errors at some point and you'll be good!
