### ISSUE TITLE
Routes MVP Review

### ISSUE THREAD

**Issue by minucos** [minucos/Straya#3]
Hi Elliot

I think I have completed the Route MVP of my project. Let me know what you think, I'm sure I've missed out on some details.

I will note that there is a bit of an issue when creating a new route. The google API doesn't like the amount of queries I am making so occasionally blocks the route from rendering (returns a QUERY LIMIT response). The map still shows, but with no path. Refreshing the page brings it up.

If you have any advice how to get around that sort of issue?

Cheers

Andy

**Comment by evhumphrey** [comment]
Cool!

Some feedback: 

- [ ] Increase the horizontal padding on the inputs for the route form
- [ ] Im getting a 500 error when trying to save a route

Regarding the API limiting queries, don't worry about that for now

**Comment by minucos** [comment]
These have been fixed, thanks!
